########################################################################
#
# title:       Docker Compose YAML file for Virtual-Vehicles Project
# author:      Gary A. Stafford (https://programmaticponderings.com)
# url:         https://github.com/garystafford/virtual-vehicles-docker  
# description: Pulls (4) images, builds (5) images, and builds (10) containers,
#              for the Virtual-Vehicles Java microservices example REST API
# to run:      docker-compose -p <your_project_name_here> up -d
#
########################################################################

graphite:
  image: hopsoft/graphite-statsd:latest
  ports:
   - "8570:80"

mongoAuthentication:
  image: mongo:latest

mongoValet:
  image: mongo:latest

mongoMaintenance:
  image: mongo:latest

mongoVehicle:
  image: mongo:latest

authentication:
  build: authentication/
  links:
   - graphite
   - mongoAuthentication

valet:
  build: valet/
  links:
   - graphite
   - mongoValet
   - authentication

maintenance:
  build: maintenance/
  links:
   - graphite
   - mongoMaintenance
   - authentication

vehicle:
  build: vehicle/
  links:
   - graphite
   - mongoVehicle
   - authentication

nginx:
  build: nginx/
  ports:
   - "80:80"
  links:
   - authentication
   - maintenance
   - valet
   - vehicle