  ########################################################################
#
# title:       Docker Compose YAML file for Virtual-Vehicles Project
# author:      Gary A. Stafford (https://programmaticponderings.com)
# url:         https://github.com/garystafford/virtual-vehicles-docker  
# description: Pulls (5) images, builds (5) images, and builds (11) containers,
#              for the Virtual-Vehicles Java microservices example REST API
# to run:      docker-compose -p <your_project_name_here> up -d
#
########################################################################

mongoauthentication:
  build: mongo/
#  volumes:
#    - "/home/docker/data:/data/db"

mongovalet:
  build: mongo/
#  volumes:
#    - "/home/docker/data:/data/db"

mongomaintenance:
  build: mongo/
#  volumes:
#    - "/home/docker/data:/data/db"

mongovehicle:
  build: mongo/
#  volumes:
#    - "/home/docker/data:/data/db"

authentication:
  build: authentication/
  links:
   - graphite
   - mongoauthentication
   - "ambassador:nginx"
   - elk
  expose:
   - "8587"

valet:
  build: valet/
  links:
   - graphite
   - mongovalet
   - "ambassador:nginx"
  expose:
   - "8585"

maintenance:
  build: maintenance/
  links:
   - graphite
   - mongomaintenance
   - "ambassador:nginx"
  expose:
   - "8583"

vehicle:
  build: vehicle/
  links:
   - graphite
   - mongovehicle
   - "ambassador:nginx"
  expose:
   - "8581"

graphite:
  image: hopsoft/graphite-statsd:latest
  ports:
   - "8500:80"

nginx:
  build: nginx/
  ports:
   - "80:80"
  links:
   - "ambassador:vehicle"
   - "ambassador:valet"
   - "ambassador:authentication"
   - "ambassador:maintenance"

ambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name jenkins_nginx_1 -name jenkins_authentication_1 -name jenkins_maintenance_1 -name jenkins_valet_1 -name jenkins_vehicle_1"

elk:
  build: elk/
  ports:
    - "8200:80"
    - "5000:5000"
    - "5000:5000/udp"
    - "9200:9200"
  expose:
   - "5000"

logspout:
  build: logspout/
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - elk
  ports:
   - "8000:80"
  environment:
    - ROUTE_URIS=logstash://elk:5000